### ISSUE TITLE
clone 下来nuget还原不行啊

### ISSUE THREAD

**Issue by gitlsl** [huoshan12345/WebQQWeChat#4]
尝试还原程序包出错，不支持给定路径。。，
另外  你用 netcore写的 dll   我net46 能直接调吗 还是说要把源码编译成4。6？

**Comment by huoshan12345** [comment]
现在拉取一下试试。目前一直在重构，所以很有可能拉到的版本编译不了。
1.是因为vs自带的nuget版本老不支持一些新功能，不过我已经把用到新功能的地方改了，没问题了。
2.取决于哪个dll，如果是webqqcore的，可以的，因为目标框架是.net core和.net 451
如果是webwechat的话，需要至少.net 461

题外话，net46有bug，建议升级到461
