### ISSUE TITLE
WebWeChat项目在确认登录后出现异常

### ISSUE THREAD

**Issue by khao1110** [huoshan12345/WebQQWeChat#5]
![image](https://cloud.githubusercontent.com/assets/5157448/20140490/7599fae6-a6c6-11e6-9710-1e93071cd7b0.png)

--------
系统为:win10 64位

**Comment by huoshan12345** [comment]
这是httpclient发送请求失败，不经常出现。我正在找解决办法

**Comment by khao1110** [comment]
我这一直是这个问题，没正常过。:(

**Comment by huoshan12345** [comment]
每次都是到这步出异常吗？
你的.net core版本是多少？

**Comment by khao1110** [comment]
.NET Core 1.0.1 - VS 2015 Tooling Preview 2
每次都异常

**Comment by huoshan12345** [comment]
现在你获取一下更新，然后再试试

**Comment by khao1110** [comment]
AccountModule移除了？
编译错误信息如下:
====================
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0246	The type or namespace name 'AccountModule' could not be found (are you missing a using directive or an assembly reference?)	WebWeChat	E:\cs\WebQQWeChat-master\src\WebWeChat\Im\Service\Impl\WeChatLogger.cs	29	
错误	CS0103	The name 'Account' does not exist in the current context	WebWeChat	E:\cs\WebQQWeChat-master\src\WebWeChat\Im\Action\GetTuringRobotReplyAction.cs	42	
错误	CS0021	Cannot apply indexing with [] to an expression of type 'ContactMember'	WebWeChat	E:\cs\WebQQWeChat-master\src\WebWeChat\Im\Action\StatusNotifyAction.cs	30	
错误	CS0021	Cannot apply indexing with [] to an expression of type 'ContactMember'	WebWeChat	E:\cs\WebQQWeChat-master\src\WebWeChat\Im\Action\StatusNotifyAction.cs	31	
错误	CS0246	The type or namespace name 'AccountModule' could not be found (are you missing a using directive or an assembly reference?)	WebWeChat	E:\cs\WebQQWeChat-master\src\WebWeChat\Im\WebWeChatClient.cs	38	
错误	CS0246	The type or namespace name 'AccountModule' could not be found (are you missing a using directive or an assembly reference?)	WebWeChat	E:\cs\WebQQWeChat-master\src\WebWeChat\Program.cs	59	
错误	CS0103	当前上下文中不存在名称“Account”	WebWeChat..NET Framework 4.6.1, WebWeChat..NETCoreApp,Version=v1.1	E:\cs\WebQQWeChat-master\src\WebWeChat\Im\Action\GetTuringRobotReplyAction.cs	42	活动
错误	CS0021	无法将带 [] 的索引应用于“ContactMember”类型的表达式	WebWeChat..NET Framework 4.6.1, WebWeChat..NETCoreApp,Version=v1.1	E:\cs\WebQQWeChat-master\src\WebWeChat\Im\Action\StatusNotifyAction.cs	30	活动
错误	CS0021	无法将带 [] 的索引应用于“ContactMember”类型的表达式	WebWeChat..NET Framework 4.6.1, WebWeChat..NETCoreApp,Version=v1.1	E:\cs\WebQQWeChat-master\src\WebWeChat\Im\Action\StatusNotifyAction.cs	31	活动
错误	CS0246	未能找到类型或命名空间名“AccountModule”(是否缺少 using 指令或程序集引用?)	WebWeChat..NET Framework 4.6.1, WebWeChat..NETCoreApp,Version=v1.1	E:\cs\WebQQWeChat-master\src\WebWeChat\Im\Service\Impl\WeChatLogger.cs	29	活动
错误	CS0246	未能找到类型或命名空间名“AccountModule”(是否缺少 using 指令或程序集引用?)	WebWeChat..NET Framework 4.6.1, WebWeChat..NETCoreApp,Version=v1.1	E:\cs\WebQQWeChat-master\src\WebWeChat\Im\WebWeChatClient.cs	38	活动
错误	CS0246	未能找到类型或命名空间名“AccountModule”(是否缺少 using 指令或程序集引用?)	WebWeChat..NET Framework 4.6.1, WebWeChat..NETCoreApp,Version=v1.1	E:\cs\WebQQWeChat-master\src\WebWeChat\Program.cs	59	活动

**Comment by huoshan12345** [comment]
已更
AccountModule移除了，放到session里面了

**Comment by khao1110** [comment]
编译正常，但依旧是请求失败.

**Comment by gitlsl** [comment]
@khao1110 net4.6 能直接引用 core 的dll 吗 有没什么要求的 ， 我也试试他这个

**Comment by huoshan12345** [comment]
@gitlsl 可以直接引，只要选择core编译到.net平台的那个dll就行

**Comment by khao1110** [comment]
@gitlsl 生成的有.net版本的dll,试了下好像也可以直接引用netcore的dll

**Comment by khao1110** [comment]
请求失败的问题搞定，怀疑和本机的证书有关，导致部分https请求失败。
又发现了个问题：在手机上发送完信息后，会有下面的错误信息产生:
Action=GetTuringRobotReplyAction, Result=错误, ErrorCode=ParameterError, ErrorMsg=_key, StackTrace=

**Comment by khao1110** [comment]
请求失败的问题搞定，怀疑和本机的证书有关，导致部分https请求失败。
又发现了个问题：在手机上发送完信息后，会有下面的错误信息产生:
Action=GetTuringRobotReplyAction, Result=错误, ErrorCode=ParameterError, ErrorMsg=_key, StackTrace=

**Comment by huoshan12345** [comment]
@khao1110 那是因为获取图灵机器人回复需要一个key，如果用不到的话把自动回复给注释了就行了（在全局listener里面）
