### ISSUE TITLE
对于 WebWeChat 项目，无法还原 NuGet 包，找不到 FclEx.Component

### ISSUE THREAD

**Issue by jijiechen** [huoshan12345/WebQQWeChat#7]
Clone 下来之后，运行 dotnet restore 会提示如图错误，无法还原和编译项目：

![wx20170822-132911](https://user-images.githubusercontent.com/1180092/29550005-026a6908-873e-11e7-9abf-f810d4d5e767.png)

看起来 FclEx.Component 是一个私有维护的包，是不是被删掉了？

**Comment by huoshan12345** [comment]
马上更新

**Comment by huoshan12345** [comment]
已修
