### ISSUE TITLE
二维码获取成功，手机QQ登录成功，但是收不到消息

### ISSUE THREAD

**Issue by zhouwensi** [huoshan12345/WebQQWeChat#8]
二维码获取成功，手机QQ登录成功，但是收不到消息
提示：

> 00:13:16> [Action=CheckQRCodeAction, Type=EvtRetry, RetryTimes=1][ErrorCode=ErrorHttpStatus, ErrorMsg=Forbidden]

**Comment by huoshan12345** [comment]
现在是连官方的webqq都收不到消息（只能登录和发送消息，原有的心跳http请求都没有了），po主也不知道该怎么办了

**Comment by Liberxue** [comment]
我做的一个 那去玩吧
https://github.com/Liberxue/WechatYUNchart

#### 微信多开多账号机器人 云客服系统 微商营销 系统web协议一键登录
非公众号微信机器人微信群管家  微信自动回复 微信定时发送消息 微信多账号登录

### 逆向是工具，是我们学习他人软件的方法，而不是用来做一些非法的事情。

- 微信网页版本协议多开
 
- 一键登录
 
- 红包数量提醒
 
- wx用户识别男女签名备注，群发
 
- 自动发消息 定时发消息 群消息监控
 
- 机器人回复 ，定时回复，超时回复
 
- 聊天记录保存，聊天记录查看
 
git.oschina ： http://git.oschina.net/bolanzw/WechatYUNchart

 
 
##### 即时通讯交流：https://gitter.im/wechatliberxue/Lobby#
 
##### Issues提交：https://github.com/Liberxue/WechatYUNchart/issues 
 
### 协议分析：http://www.liberxue.com/%E5%BE%AE%E4%BF%A1/wechart.html
 
 
![](http://ot1cc1u9t.bkt.clouddn.com/17-7-13/99226513.jpg)


![](http://ot1cc1u9t.bkt.clouddn.com/17-7-13/16191614.jpg)

**Comment by zhouwensi** [comment]
微信的吗？我想要的是QQ群的

**Comment by huoshan12345** [comment]
今天更新了一下，webqq已经可以正常登录和接收消息了。
