### ISSUE TITLE
请问有WebWechat framework 的吗

### ISSUE THREAD

**Issue by h0730303779** [huoshan12345/WebQQWeChat#9]

**Comment by huoshan12345** [comment]
https://github.com/huoshan12345/WebQQWeChat/tree/master/src/WebWeChat
这个就是了

**Comment by h0730303779** [comment]
谢谢 
不过这个不支持 framework  比如你的 WebQQCore 那样支持双平台的

**Comment by huoshan12345** [comment]
这个是netstandard的，双平台当然都支持啊（net461+）
